
import React, { useMemo, useState, useEffect } from 'react';
import { Vehicle, Expense, ExpenseCategory, StoreExpense, OpexCategory } from '../types';
import { Card } from '../components/ui/Card';
import { formatCurrency, maskCurrencyInput, parseCurrencyInput, calculateRealProfit } from '../lib/utils';
import { Search, Filter, Wrench, FileText, Megaphone, Gauge, AlertCircle, Calendar, Tag, Car, User, Building2, Plus, Trash2, TrendingUp, TrendingDown, DollarSign, Wallet } from 'lucide-react';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from 'recharts';
import { Button } from '../components/ui/Button';
import { useVelohub } from '../contexts/VelohubContext';
import { ApiService } from '../services/api';

interface ExpensesListProps {
  vehicles: Vehicle[];
}

const OPEX_CATEGORIES: { id: OpexCategory; label: string }[] = [
    { id: 'rent', label: 'Aluguel' },
    { id: 'utilities', label: 'Energia/Água/Net' },
    { id: 'payroll', label: 'Folha Pagamento (Fixo)' },
    { id: 'marketing_store', label: 'Marketing da Loja' },
    { id: 'software', label: 'Sistemas/Software' },
    { id: 'taxes', label: 'Impostos' },
    { id: 'office', label: 'Escritório/Limpeza' },
    { id: 'other', label: 'Outros' }
];

export const ExpensesList: React.FC<ExpensesListProps> = ({ vehicles }) => {
  const { user } = useVelohub();
  const [activeTab, setActiveTab] = useState<'vehicles' | 'opex' | 'result'>('vehicles');
  
  // States for Vehicles Tab
  const [vehicleSearch, setVehicleSearch] = useState('');
  
  // States for OPEX Tab
  const [storeExpenses, setStoreExpenses] = useState<StoreExpense[]>([]);
  const [isAddingOpex, setIsAddingOpex] = useState(false);
  const [newOpex, setNewOpex] = useState<{ desc: string, amount: string, category: OpexCategory, date: string }>({
      desc: '', amount: '', category: 'utilities', date: new Date().toISOString().split('T')[0]
  });

  // Load OPEX on mount
  useEffect(() => {
      if (user) {
          loadOpex();
      }
  }, [user]);

  const loadOpex = async () => {
      if (!user) return;
      const data = await ApiService.getStoreExpenses(user.storeId);
      setStoreExpenses(data);
  };

  const handleAddOpex = async () => {
      if (!user) return;
      if (!newOpex.desc || !newOpex.amount) return alert("Preencha descrição e valor");

      const expense: StoreExpense = {
          id: '', // Generated by API
          storeId: user.storeId,
          description: newOpex.desc,
          amount: parseCurrencyInput(newOpex.amount),
          date: newOpex.date,
          category: newOpex.category,
          paid: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString()
      };

      await ApiService.createStoreExpense(expense);
      setIsAddingOpex(false);
      setNewOpex({ desc: '', amount: '', category: 'utilities', date: new Date().toISOString().split('T')[0] });
      loadOpex();
  };

  const handleDeleteOpex = async (id: string) => {
      if (window.confirm("Excluir esta despesa?")) {
          await ApiService.deleteStoreExpense(id);
          loadOpex();
      }
  };

  // --- CALCULATIONS FOR RESULT TAB ---
  const financialResult = useMemo(() => {
      // 1. Gross Profit from Sold Vehicles (Receita - (Compra + Gastos Veículo))
      const soldVehicles = vehicles.filter(v => v.status === 'sold');
      const grossProfit = soldVehicles.reduce((acc, v) => acc + calculateRealProfit(v), 0);
      const totalRevenue = soldVehicles.reduce((acc, v) => acc + (v.soldPrice || 0), 0);

      // 2. Total OPEX (Paid)
      const totalOpex = storeExpenses.reduce((acc, e) => acc + e.amount, 0);

      // 3. Net Result
      const netResult = grossProfit - totalOpex;

      return {
          grossProfit,
          totalOpex,
          netResult,
          totalRevenue,
          salesCount: soldVehicles.length
      };
  }, [vehicles, storeExpenses]);

  // --- VEHICLE EXPENSES LOGIC ---
  const allVehicleExpenses = useMemo(() => {
      const flat: any[] = [];
      vehicles.forEach(v => {
          v.expenses.forEach(e => {
              flat.push({ ...e, vehicleName: `${v.make} ${v.model}`, vehiclePlate: v.plate || 'S/ Placa', type: 'expense' });
          });
          if (v.status === 'sold' && v.saleCommission && v.saleCommission > 0) {
              flat.push({
                  id: `comm-${v.id}`,
                  description: 'Comissão de Venda',
                  amount: v.saleCommission,
                  date: v.soldDate || v.updatedAt,
                  category: 'salary',
                  vehicleName: `${v.make} ${v.model}`,
                  vehiclePlate: v.plate || 'S/ Placa',
                  employeeName: v.saleCommissionTo,
                  type: 'commission'
              });
          }
      });
      return flat.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  }, [vehicles]);

  const filteredVehicleExpenses = allVehicleExpenses.filter(e => 
      e.vehicleName.toLowerCase().includes(vehicleSearch.toLowerCase()) || 
      e.description.toLowerCase().includes(vehicleSearch.toLowerCase())
  );

  const COLORS = ['#10b981', '#3b82f6', '#f59e0b', '#ec4899', '#8b5cf6', '#64748b', '#06b6d4'];

  return (
    <div className="space-y-6 animate-fade-in">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div>
                <h1 className="text-3xl font-bold text-white">Central Financeira</h1>
                <p className="text-slate-400">Separação clara entre custos de estoque (CMV) e despesas da loja (OPEX).</p>
            </div>
            <div className="flex bg-slate-900 p-1 rounded-xl border border-slate-800">
                <button 
                    onClick={() => setActiveTab('vehicles')}
                    className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${activeTab === 'vehicles' ? 'bg-slate-800 text-white shadow' : 'text-slate-400 hover:text-white'}`}
                >
                    Custos Veículos (CMV)
                </button>
                <button 
                    onClick={() => setActiveTab('opex')}
                    className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${activeTab === 'opex' ? 'bg-slate-800 text-white shadow' : 'text-slate-400 hover:text-white'}`}
                >
                    Despesas Loja (OPEX)
                </button>
                <button 
                    onClick={() => setActiveTab('result')}
                    className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${activeTab === 'result' ? 'bg-emerald-600 text-white shadow' : 'text-slate-400 hover:text-white'}`}
                >
                    Resultado Líquido
                </button>
            </div>
        </div>

        {/* --- ABA 1: CUSTOS DE VEÍCULOS (CMV) --- */}
        {activeTab === 'vehicles' && (
            <div className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <Card>
                        <div className="flex items-center gap-3 mb-2">
                            <Wrench className="text-amber-400" />
                            <h3 className="text-sm font-medium text-slate-400">Total Gasto em Reformas</h3>
                        </div>
                        <p className="text-2xl font-bold text-white">
                            {formatCurrency(allVehicleExpenses.reduce((acc, e) => acc + (e.category !== 'salary' ? e.amount : 0), 0))}
                        </p>
                    </Card>
                    <Card>
                        <div className="flex items-center gap-3 mb-2">
                            <User className="text-indigo-400" />
                            <h3 className="text-sm font-medium text-slate-400">Total em Comissões</h3>
                        </div>
                        <p className="text-2xl font-bold text-white">
                            {formatCurrency(allVehicleExpenses.reduce((acc, e) => acc + (e.category === 'salary' ? e.amount : 0), 0))}
                        </p>
                    </Card>
                </div>

                <Card title="Detalhamento por Carro">
                    <div className="mb-4 relative">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={18} />
                        <input 
                            type="text" 
                            placeholder="Buscar despesa..." 
                            value={vehicleSearch}
                            onChange={e => setVehicleSearch(e.target.value)}
                            className="w-full bg-slate-950 border border-slate-800 text-white rounded-lg pl-10 p-2.5 outline-none focus:border-indigo-500"
                        />
                    </div>
                    <div className="max-h-[500px] overflow-y-auto">
                        <table className="w-full text-left border-collapse">
                            <thead className="bg-slate-950 text-slate-400 text-sm sticky top-0">
                                <tr>
                                    <th className="p-3">Data</th>
                                    <th className="p-3">Veículo</th>
                                    <th className="p-3">Descrição</th>
                                    <th className="p-3 text-right">Valor</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-800 text-sm">
                                {filteredVehicleExpenses.map((e, idx) => (
                                    <tr key={idx} className="hover:bg-slate-800/50">
                                        <td className="p-3 text-slate-400">{new Date(e.date).toLocaleDateString()}</td>
                                        <td className="p-3 text-white font-medium">
                                            {e.vehicleName} <span className="text-xs text-slate-500 block">{e.vehiclePlate}</span>
                                        </td>
                                        <td className="p-3 text-slate-300">
                                            {e.description}
                                            {e.type === 'commission' && <span className="ml-2 text-[10px] bg-indigo-500/20 text-indigo-400 px-1.5 py-0.5 rounded">Comissão</span>}
                                        </td>
                                        <td className="p-3 text-right font-bold text-white">{formatCurrency(e.amount)}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </Card>
            </div>
        )}

        {/* --- ABA 2: OPEX (DESPESAS DA LOJA) --- */}
        {activeTab === 'opex' && (
            <div className="space-y-6">
                <div className="flex justify-between items-center">
                    <h2 className="text-xl font-bold text-white flex items-center gap-2">
                        <Building2 className="text-indigo-500" />
                        Despesas Operacionais
                    </h2>
                    <Button onClick={() => setIsAddingOpex(true)} icon={<Plus size={18} />}>Lançar Despesa</Button>
                </div>

                {isAddingOpex && (
                    <div className="bg-slate-800/50 border border-slate-700 p-4 rounded-xl animate-fade-in">
                        <h3 className="text-white font-bold mb-4 text-sm">Nova Despesa da Loja</h3>
                        <div className="grid grid-cols-1 md:grid-cols-5 gap-4 items-end">
                            <div className="md:col-span-1">
                                <label className="text-xs text-slate-400 block mb-1">Categoria</label>
                                <select 
                                    className="w-full bg-slate-900 border border-slate-700 rounded-lg p-2.5 text-white text-sm"
                                    value={newOpex.category}
                                    onChange={e => setNewOpex({...newOpex, category: e.target.value as OpexCategory})}
                                >
                                    {OPEX_CATEGORIES.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}
                                </select>
                            </div>
                            <div className="md:col-span-2">
                                <label className="text-xs text-slate-400 block mb-1">Descrição</label>
                                <input 
                                    className="w-full bg-slate-900 border border-slate-700 rounded-lg p-2.5 text-white text-sm" 
                                    placeholder="Ex: Aluguel Fevereiro"
                                    value={newOpex.desc}
                                    onChange={e => setNewOpex({...newOpex, desc: e.target.value})}
                                />
                            </div>
                            <div className="md:col-span-1">
                                <label className="text-xs text-slate-400 block mb-1">Valor</label>
                                <input 
                                    className="w-full bg-slate-900 border border-slate-700 rounded-lg p-2.5 text-white text-sm font-bold" 
                                    placeholder="R$ 0,00"
                                    value={newOpex.amount}
                                    onChange={e => setNewOpex({...newOpex, amount: maskCurrencyInput(e.target.value)})}
                                />
                            </div>
                            <div className="flex gap-2">
                                <Button onClick={handleAddOpex} className="flex-1">Salvar</Button>
                                <Button variant="ghost" onClick={() => setIsAddingOpex(false)} className="px-3"><Trash2 size={18} /></Button>
                            </div>
                        </div>
                    </div>
                )}

                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <Card className="md:col-span-2">
                        <table className="w-full text-left border-collapse">
                            <thead className="text-slate-400 text-sm border-b border-slate-800">
                                <tr>
                                    <th className="p-3">Data</th>
                                    <th className="p-3">Descrição</th>
                                    <th className="p-3">Categoria</th>
                                    <th className="p-3 text-right">Valor</th>
                                    <th className="p-3 w-10"></th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-800 text-sm">
                                {storeExpenses.map(item => (
                                    <tr key={item.id} className="hover:bg-slate-800/30 group">
                                        <td className="p-3 text-slate-400">{new Date(item.date).toLocaleDateString()}</td>
                                        <td className="p-3 text-white">{item.description}</td>
                                        <td className="p-3">
                                            <span className="bg-slate-800 text-slate-300 px-2 py-1 rounded-full text-xs border border-slate-700">
                                                {OPEX_CATEGORIES.find(c => c.id === item.category)?.label}
                                            </span>
                                        </td>
                                        <td className="p-3 text-right text-white font-bold">{formatCurrency(item.amount)}</td>
                                        <td className="p-3 text-right">
                                            <button onClick={() => handleDeleteOpex(item.id)} className="text-slate-600 hover:text-rose-500 opacity-0 group-hover:opacity-100 transition-all">
                                                <Trash2 size={16} />
                                            </button>
                                        </td>
                                    </tr>
                                ))}
                                {storeExpenses.length === 0 && (
                                    <tr><td colSpan={5} className="p-8 text-center text-slate-500">Nenhuma despesa operacional lançada.</td></tr>
                                )}
                            </tbody>
                        </table>
                    </Card>
                    <Card>
                        <h3 className="text-sm font-bold text-white mb-4">Resumo OPEX</h3>
                        <div className="h-48">
                            <ResponsiveContainer width="100%" height="100%">
                                <PieChart>
                                    <Pie data={
                                        Object.entries(storeExpenses.reduce((acc: any, curr) => {
                                            acc[curr.category] = (acc[curr.category] || 0) + curr.amount;
                                            return acc;
                                        }, {})).map(([name, value]) => ({ name, value }))
                                    } dataKey="value" innerRadius={40} outerRadius={60} paddingAngle={2}>
                                        {OPEX_CATEGORIES.map((entry, index) => (
                                            <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                                        ))}
                                    </Pie>
                                    <Tooltip 
                                        contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155', borderRadius: '8px', color: '#fff' }}
                                        formatter={(value: number) => formatCurrency(value)}
                                    />
                                </PieChart>
                            </ResponsiveContainer>
                        </div>
                        <div className="text-center mt-2">
                            <p className="text-slate-400 text-xs uppercase">Total OPEX</p>
                            <p className="text-2xl font-bold text-white">{formatCurrency(storeExpenses.reduce((acc, e) => acc + e.amount, 0))}</p>
                        </div>
                    </Card>
                </div>
            </div>
        )}

        {/* --- ABA 3: RESULTADO LÍQUIDO --- */}
        {activeTab === 'result' && (
            <div className="space-y-8 animate-slide-in-right">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-center">
                    <div className="bg-slate-900 border border-slate-800 p-6 rounded-2xl">
                        <p className="text-slate-400 text-sm uppercase font-bold mb-2">Lucro Bruto (Veículos)</p>
                        <p className="text-3xl font-bold text-emerald-400">{formatCurrency(financialResult.grossProfit)}</p>
                        <p className="text-xs text-slate-500 mt-2">Após descontar compra e gastos dos carros</p>
                    </div>
                    <div className="flex items-center justify-center">
                        <div className="bg-slate-800 p-3 rounded-full">
                            <TrendingDown size={24} className="text-rose-400" />
                        </div>
                    </div>
                    <div className="bg-slate-900 border border-slate-800 p-6 rounded-2xl">
                        <p className="text-slate-400 text-sm uppercase font-bold mb-2">Despesas Loja (OPEX)</p>
                        <p className="text-3xl font-bold text-rose-400">{formatCurrency(financialResult.totalOpex)}</p>
                        <p className="text-xs text-slate-500 mt-2">Aluguel, Luz, Salários Fixos, etc.</p>
                    </div>
                </div>

                <div className={`p-8 rounded-3xl border-2 text-center transform hover:scale-[1.01] transition-transform ${financialResult.netResult >= 0 ? 'bg-emerald-900/20 border-emerald-500/50' : 'bg-rose-900/20 border-rose-500/50'}`}>
                    <h3 className="text-xl font-bold text-white uppercase tracking-widest mb-2">Resultado Operacional Líquido</h3>
                    <div className="text-5xl md:text-7xl font-black text-white tracking-tighter my-4">
                        {formatCurrency(financialResult.netResult)}
                    </div>
                    <p className={`text-sm font-medium ${financialResult.netResult >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                        {financialResult.netResult >= 0 ? 'Lucro Real no Bolso' : 'Prejuízo Operacional'}
                    </p>
                </div>

                <div className="text-center text-slate-500 text-sm">
                    <p>Baseado em {financialResult.salesCount} vendas realizadas e {storeExpenses.length} despesas operacionais lançadas.</p>
                </div>
            </div>
        )}
    </div>
  );
};
